############
# Entities #
############

type Session @entity(immutable: false) {
  id: ID! # sessionId
  sessionId: BigInt!
  deployer: Bytes!
  parentMarket: Bytes!
  outcomeCount: BigInt!
  deployedChildCount: BigInt!
  openedAt: BigInt!
  completedAt: BigInt!
  marketName: String!
  outcomes: [String!]!
  keyword: String!
  children: [ChildMarket!]! @derivedFrom(field: "session")
  transactionHash: Bytes!
}

type ChildMarket @entity(immutable: true) {
  id: ID! # childMarket address
  session: Session!
  parentOutcomeIndex: BigInt!
  parentOutcome: String!
  deployedAt: BigInt!
  marketName: String!
  lowerBound: BigInt!
  upperBound: BigInt!
  keyword: String!
  transactionHash: Bytes!
}

type _Schema_
  @fulltext(
    name: "marketSearch"
    language: en
    algorithm: rank
    include: [{ entity: "Session", fields: [{ name: "keyword" }] }]
  )
  @fulltext(
    name: "childMarketSearch"
    language: en
    algorithm: rank
    include: [{ entity: "ChildMarket", fields: [{ name: "keyword" }] }]
  )
