#!/usr/bin/env bash
# Regenerates config.yaml from config.template.yaml, filling every contract's address, and
# each chain's start_block, from that network's deployment artifacts.
#
#   yarn update              every chain in the template that has artifacts
#   yarn update:local        just the local hardhat chain
#   bash scripts/update.sh gnosis [...]
#
# The template drives everything: whichever contracts a chain declares are the ones looked
# up, by name, as `<deployments>/<Name>.json`. Adding a contract to the template is the
# only step needed to have it filled in here.
#
# Named networks must resolve - asking for one that has not been deployed is an error.
# In the default all-chains mode a missing artifact is a skip, so a literal address for a
# real network survives a machine that has never deployed to it.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INDEXER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$INDEXER_DIR/config.yaml"
TEMPLATE="$INDEXER_DIR/config.template.yaml"

log() { printf '[indexer/update] %s\n' "$*"; }
die() {
  log "error: $*"
  exit 1
}

# chain id -> the network whose deployments directory holds its artifacts
network_for() {
  case "$1" in
  31337) echo localhost ;;
  100) echo gnosis ;;
  *) return 1 ;;
  esac
}

deployments_dir() {
  local network="$1" candidate
  for candidate in \
    "$INDEXER_DIR/node_modules/@foresight/contracts/deployments/$network" \
    "$INDEXER_DIR/../../node_modules/@foresight/contracts/deployments/$network"; do
    [[ -d "$candidate" ]] && {
      echo "$candidate"
      return 0
    }
  done

  return 1
}

# yq path to one contract inside one chain
contract_at() { printf '(.chains[] | select(.id == %s) | .contracts[] | select(.name == "%s"))' "$1" "$2"; }

declares() { [[ "$(yq "$1 | has(\"$2\")" "$TEMPLATE")" == "true" ]]; }

command -v jq >/dev/null || die "jq not installed"
command -v yq >/dev/null || die "yq not installed"
[[ -f "$TEMPLATE" ]] || die "missing template: $TEMPLATE"

# no arguments means every chain in the template
requested=("$@")

wanted() {
  local candidate
  ((${#requested[@]} == 0)) && return 0
  for candidate in "${requested[@]}"; do
    [[ "$candidate" == "$1" ]] && return 0
  done

  return 1
}

{
  echo '# THIS FILE IS AUTO-GENERATED BY scripts/update.sh FROM config.template.yaml, ANY CHANGES WILL BE LOST.'
  cat "$TEMPLATE"
} >"$CONFIG"

filled=0
matched=()
for chainId in $(yq '.chains[].id' "$TEMPLATE"); do
  network="$(network_for "$chainId")" || die "chain $chainId in the template has no known network, add it to network_for()"

  wanted "$network" || continue
  matched+=("$network")

  deployments="$(deployments_dir "$network")" || {
    # asking for a network by name and getting nothing is a mistake worth stopping on;
    # in all-chains mode it just means that network is not deployed from here
    ((${#requested[@]} > 0)) && die "$network has no deployments directory, deploy it first"
    log "· $chainId ($network): nothing deployed, keeping the template values"
    continue
  }

  earliest=""
  for name in $(yq ".chains[] | select(.id == $chainId) | .contracts[].name" "$TEMPLATE"); do
    artifact="$deployments/$name.json"
    contract="$(contract_at "$chainId" "$name")"

    [[ -f "$artifact" ]] || {
      ((${#requested[@]} > 0)) && die "$network has no $name deployment at $artifact"
      log "· $chainId ($network): no $name artifact, keeping the template value"
      continue
    }

    address="$(jq -r '.address' "$artifact")"
    startBlock="$(jq -r '.receipt.blockNumber' "$artifact")"
    [[ "$address" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "invalid address in $artifact: $address"
    [[ "$startBlock" =~ ^[0-9]+$ ]] || die "invalid receipt.blockNumber in $artifact: $startBlock"

    # the address is quoted explicitly: bare 0x-prefixed hex is an integer to a YAML
    # parser, and 40 hex digits would resolve to a number rather than an address
    yq -i "($contract | .address) = [\"$address\"] | ($contract | .address[]) style=\"double\"" "$CONFIG"

    # a contract only gets its own start_block if the template asked for one, since it
    # overrides the chain's
    if declares "$contract" start_block; then
      yq -i "($contract | .start_block) = $startBlock" "$CONFIG"
    fi

    if [[ -z "$earliest" || "$startBlock" -lt "$earliest" ]]; then earliest="$startBlock"; fi

    log "✓ $chainId ($network): $name $address from block $startBlock"
    filled=$((filled + 1))
  done

  # the chain starts at its earliest contract - anything before that has nothing to index
  if [[ -n "$earliest" ]] && declares "(.chains[] | select(.id == $chainId))" start_block; then
    yq -i "(.chains[] | select(.id == $chainId) | .start_block) = $earliest" "$CONFIG"
  fi
done

# a name that matched no chain is a typo, not a no-op. Both arrays are expanded with the
# `+` guard: under `set -u`, bash 3.2 treats an empty array as unbound.
for network in ${requested[@]+"${requested[@]}"}; do
  found=false
  for candidate in ${matched[@]+"${matched[@]}"}; do
    [[ "$candidate" == "$network" ]] && found=true
  done
  [[ "$found" == true ]] || die "'$network' matches no chain in the template"
done

# comments are excluded: the template explains the placeholder convention by name
grep -v '^\s*#' "$CONFIG" | grep -q '_PLACEHOLDER_' &&
  log "warning: config.yaml still has placeholders - deploy the missing network, or put its address in the template"

log "wrote config.yaml ($filled contract(s) filled)"
