#!/usr/bin/env bash
# Generates one config per network from config.template.yaml, filling each contract's
# address, and the chain's start_block, from that network's deployment artifacts.
#
#   yarn update:local        writes config.localhost.yaml
#   yarn update:gnosis       writes config.gnosis.yaml
#   bash scripts/update.sh localhost gnosis
#
# The template drives everything: whichever contracts a chain declares are the ones looked
# up, by name, as `<deployments>/<Name>.json`. Adding a contract to the template is the
# only step needed to have it filled in here.
#
# `##` lines in the template are notes for its editors and are stripped on the way out;
# single `#` comments are copied into the generated config.
#
# At least one network is required, and every one named must resolve. A config carries only
# its own chain: envio syncs every chain the file declares, and entity ids are not
# chain-namespaced, so one config, one chain.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INDEXER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE="$INDEXER_DIR/config.template.yaml"

log() { printf '[indexer/update] %s\n' "$*"; }
die() {
  log "error: $*"
  exit 1
}

# chain id -> the network whose deployments directory holds its artifacts
network_for() {
  case "$1" in
  31337) echo localhost ;;
  100) echo gnosis ;;
  *) return 1 ;;
  esac
}

config_for() { echo "$INDEXER_DIR/config.$1.yaml"; }

deployments_dir() {
  local network="$1" candidate
  for candidate in \
    "$INDEXER_DIR/node_modules/@foresight/contracts/deployments/$network" \
    "$INDEXER_DIR/../../node_modules/@foresight/contracts/deployments/$network"; do
    [[ -d "$candidate" ]] && {
      echo "$candidate"
      return 0
    }
  done

  return 1
}

# yq path to one contract inside one chain
contract_at() { printf '(.chains[] | select(.id == %s) | .contracts[] | select(.name == "%s"))' "$1" "$2"; }

declares() { [[ "$(yq "$1 | has(\"$2\")" "$TEMPLATE")" == "true" ]]; }

command -v jq >/dev/null || die "jq not installed"
command -v yq >/dev/null || die "yq not installed"
[[ -f "$TEMPLATE" ]] || die "missing template: $TEMPLATE"

requested=("$@")
((${#requested[@]} > 0)) || die "name at least one network, e.g. 'localhost' or 'gnosis'"

# network -> chain id, from the template, so the template stays the single source of truth
chain_for() {
  local chainId
  for chainId in $(yq '.chains[].id' "$TEMPLATE"); do
    [[ "$(network_for "$chainId")" == "$1" ]] && {
      echo "$chainId"
      return 0
    }
  done

  return 1
}

known=()
for chainId in $(yq '.chains[].id' "$TEMPLATE"); do
  network_for "$chainId" >/dev/null || die "chain $chainId in the template has no known network, add it to network_for()"
  known+=("$(network_for "$chainId")")
done

# every requested name has to resolve to a chain and to artifacts before any config is
# written, so a bad argument leaves the existing ones alone
for network in "${requested[@]}"; do
  chain_for "$network" >/dev/null || die "'$network' matches no chain in the template, known: ${known[*]}"
  deployments_dir "$network" >/dev/null || die "$network has no deployments directory, deploy it first"
done

for network in "${requested[@]}"; do
  chainId="$(chain_for "$network")"
  config="$(config_for "$network")"
  deployments="$(deployments_dir "$network")"

  {
    echo "# THIS FILE IS AUTO-GENERATED BY scripts/update.sh FROM config.template.yaml, ANY CHANGES WILL BE LOST."
    grep -v '^[[:space:]]*##' "$TEMPLATE"
  } >"$config"

  # each config keeps only its own chain
  for other in $(yq '.chains[].id' "$config"); do
    [[ "$other" == "$chainId" ]] || yq -i "del(.chains[] | select(.id == $other))" "$config"
  done

  filled=0
  earliest=""
  for name in $(yq ".chains[] | select(.id == $chainId) | .contracts[].name" "$TEMPLATE"); do
    artifact="$deployments/$name.json"
    contract="$(contract_at "$chainId" "$name")"

    [[ -f "$artifact" ]] || die "$network has no $name deployment at $artifact"

    address="$(jq -r '.address' "$artifact")"
    startBlock="$(jq -r '.receipt.blockNumber' "$artifact")"
    [[ "$address" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "invalid address in $artifact: $address"
    [[ "$startBlock" =~ ^[0-9]+$ ]] || die "invalid receipt.blockNumber in $artifact: $startBlock"

    # the address is quoted explicitly: bare 0x-prefixed hex is an integer to a YAML
    # parser, and 40 hex digits would resolve to a number rather than an address
    yq -i "($contract | .address) = [\"$address\"] | ($contract | .address[]) style=\"double\"" "$config"

    # a contract only gets its own start_block if the template asked for one, since it
    # overrides the chain's
    if declares "$contract" start_block; then
      yq -i "($contract | .start_block) = $startBlock" "$config"
    fi

    if [[ -z "$earliest" || "$startBlock" -lt "$earliest" ]]; then earliest="$startBlock"; fi

    log "✓ $chainId ($network): $name $address from block $startBlock"
    filled=$((filled + 1))
  done

  # the chain starts at its earliest contract - anything before that has nothing to index
  if [[ -n "$earliest" ]] && declares "(.chains[] | select(.id == $chainId))" start_block; then
    yq -i "(.chains[] | select(.id == $chainId) | .start_block) = $earliest" "$config"
  fi

  # comments are excluded: the template explains the placeholder convention by name
  grep -v '^\s*#' "$config" | grep -q '_PLACEHOLDER_' &&
    log "warning: $(basename "$config") still has placeholders - deploy the missing contract, or put its address in the template"

  log "wrote $(basename "$config") ($filled contract(s) filled)"
done
