#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBGRAPH_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
  echo "Usage: $(basename "$0") <hardhatNetwork> <graphNetwork> [subgraphConfigPath]" >&2
  echo "Example: $(basename "$0") localhost mainnet" >&2
  echo "Example: $(basename "$0") gnosis gnosis" >&2
  exit 1
}

if [[ $# -lt 2 ]]; then
  usage
fi

hardhatNetwork="$1"
graphNetwork="$2"
subgraphConfig="${3:-$SUBGRAPH_DIR/subgraph.yaml}"
template="${subgraphConfig%.yaml}.template.yaml"
artifact="$SUBGRAPH_DIR/abis/$hardhatNetwork/SessionFactory.json"

if [[ ! -f "$template" ]]; then
  echo "Missing template: $template" >&2
  exit 1
fi

"$SCRIPT_DIR/sync-abis.sh" "$hardhatNetwork"

if [[ -f "$subgraphConfig" ]]; then
  cp "$subgraphConfig" "$subgraphConfig.bak.$(date +%s)"
fi

{
  echo '# THIS FILE IS AUTO-GENERATED BY update.sh FROM subgraph.template.yaml, ANY CHANGES WILL BE LOST.'
  cat "$template"
} >"$subgraphConfig"

if [[ ! -f "$artifact" ]]; then
  echo "SessionFactory deployment not found: $artifact" >&2
  exit 1
fi

address="$(jq -r '.address' "$artifact")"
blockNumber="$(jq -r '.receipt.blockNumber' "$artifact")"

if [[ -z "$address" || "$address" == "null" || -z "$blockNumber" || "$blockNumber" == "null" ]]; then
  echo "Invalid deployment artifact at $artifact (expected address and receipt.blockNumber)" >&2
  exit 1
fi

yq -i ".dataSources[0].network=\"$graphNetwork\"" "$subgraphConfig"
yq -i ".dataSources[0].source.address=\"$address\"" "$subgraphConfig"
yq -i ".dataSources[0].source.startBlock=$blockNumber" "$subgraphConfig"
yq -i ".dataSources[0].mapping.abis[0].file=\"./abis/$hardhatNetwork/SessionFactory.json\"" "$subgraphConfig"

echo "Updated $subgraphConfig (hardhat=$hardhatNetwork, graph=$graphNetwork)"
